export const DarkTheme ={
    palette: {
      themePrimary: '#dade00',
      themeLighterAlt: '#fefef4',
      themeLighter: '#f9fad2',
      themeLight: '#f4f5ac',
      themeTertiary: '#e9eb5e',
      themeSecondary: '#dfe21b',
      themeDarkAlt: '#c4c800',
      themeDark: '#a6a900',
      themeDarker: '#7a7c00',
      neutralLighterAlt: '#2b2b2b',
      neutralLighter: '#333333',
      neutralLight: '#414141',
      neutralQuaternaryAlt: '#4a4a4a',
      neutralQuaternary: '#515151',
      neutralTertiaryAlt: '#6f6f6f',
      neutralTertiary: '#c8c8c8',
      neutralSecondary: '#d0d0d0',
      neutralPrimaryAlt: '#dadada',
      neutralPrimary: '#ffffff',
      neutralDark: '#f4f4f4',
      black: '#f8f8f8',
      white: '#202020',
    }};