export const LightTheme = {
    palette: {
      themePrimary: '#dade00',
      themeLighterAlt: '#090900',
      themeLighter: '#232300',
      themeLight: '#414300',
      themeTertiary: '#838500',
      themeSecondary: '#c0c300',
      themeDarkAlt: '#dee117',
      themeDark: '#e3e637',
      themeDarker: '#eaec68',
      neutralLighterAlt: '#ecebe9',
      neutralLighter: '#e8e7e6',
      neutralLight: '#dedddc',
      neutralQuaternaryAlt: '#cfcecd',
      neutralQuaternary: '#c6c5c4',
      neutralTertiaryAlt: '#bebdbc',
      neutralTertiary: '#0b0b0b',
      neutralSecondary: '#0f0f0f',
      neutralPrimaryAlt: '#131313',
      neutralPrimary: '#202020',
      neutralDark: '#1a1a1a',
      black: '#1e1e1e',
      white: '#f3f2f1',
    }};